---
# tasks file for ansible-role-cockpit
- name: Install cockpit packages
  package:
    name:
      - cockpit
      - cockpit-composer
      - cockpit-machines
      - cockpit-navigator
      - cockpit-networkmanager
      - cockpit-podman
      - cockpit-session-recording
      - cockpit-storaged
      - cockpit-system

- name: Force systemd to reread config, enable and start service cockpit.socket
  systemd:
    name: cockpit.socket
    state: restarted
    daemon_reload: yes
    enabled: yes
